# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend
#   namespace: expense
#   labels:
#     proj: expense
#     app: frontend
#     tier: web
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       proj: expense
#       app: frontend
#       tier: web
#   template:
#     metadata:
#       name: frontend
#       labels:
#         proj: expense
#         app: frontend
#         tier: web
#     spec:
#      containers:
#      - name: frontend
#        image: sri8008/web:v1
#        ports:
#        - containerPort: 80

# ---

# apiVersion: v1 
# kind: Service
# metadata:
#   name: frontend
#   namespace: expense
#   labels:
#     proj: expense
# spec:
#   type: LoadBalancer
#   selector:
#     proj: expense
#     app: frontend
#     tier: web
#   ports:
#   - name: frontend
#     protocol: TCP
#     port: 80
#     targetPort: 80


apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: sri8008/web:v1
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port