apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    proj: expense
    app: frontend
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: expense
      app: frontend
      tier: web
  template:
    metadata:
      name: frontend
      labels:
        proj: expense
        app: frontend
        tier: web
    spec:
     containers:
     - name: frontend
       image: sri8008/web:v1
       ports:
       - containerPort: 80

---

apiVersion: v1 
kind: Service
metadata:
  name: frontend
  namespace: expense
  labels:
    proj: expense
spec:
  type: LoadBalancer
  selector:
    proj: expense
    app: frontend
    tier: web
  ports:
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: 80


