apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    proj: expense
    app: backend
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      proj: expense
      app: backend
      tier: api
  template:
    metadata:
      name: backend
      labels:
        proj: expense
        app: backend
        tier: api
    spec:
     containers:
     - name: backend
       image: sri8008/backend:v1
       envFrom:
       - configMapRef:
          name: backend-config
       ports:
       - containerPort: 8080

---

apiVersion: v1 
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    proj: expense
spec:
  selector:
    proj: expense
    app: backend
    tier: api
  ports:
  - name: backend
    protocol: TCP
    port: 8080
    targetPort: 8080


